name: Deploy para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infra
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: "DespesasRG"
        template: ./templates/main.bicep

    - name: Build e deploy container
      uses: azure/webapps-deploy@v2
      with:
        app-name: "despesas-app"
        images: docker.io/seuuser/imagem-backend:latest
