name: Deploy para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        submodules: true

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./backend/Dockerfile
        push: true
        tags: botalmeida/backend-despesas:latest

    - name: Deploy container para Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "quanto-gastei"
        images: docker.io/botalmeida/backend-despesas:latest
