name: Deploy para Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login ao Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker login no ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login acrdespesas.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build e push imagem backend para ACR
      run: |
        docker build -t acrdespesas.azurecr.io/backend-despesas:latest ./backend
        docker push acrdespesas.azurecr.io/backend-despesas:latest

    - name: Build e push imagem frontend para ACR
      run: |
        docker build -t acrdespesas.azurecr.io/frontend-despesas:latest ./frontend/function-app
        docker push acrdespesas.azurecr.io/frontend-despesas:latest

    - name: Deploy infraestrutura via Bicep
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-despesas
        template: infra/main.bicep
        parameters: location=westeurope

    - name: Reiniciar backend App Service
      run: |
        az webapp restart --name backend-webapp-despesas --resource-group rg-despesas

    - name: Reiniciar frontend Function App
      run: |
        az functionapp restart --name frontend-function-despesas --resource-group rg-despesas
