name: Deploy QuantoGastei Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login no ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_NAME }} --password-stdin

    - name: Build e push backend
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./backend
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

    - name: Build e push function
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/function:latest ./function
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/function:latest

    - name: Deploy infraestrutura Bicep
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-despesas
        template: infra/main.bicep
        parameters: location=northeurope
        failOnStdErr: false

    - name: Criar zip do frontend
      run: |
        cd frontend
        zip -r ../frontend.zip .

    - name: Deploy frontend zip
      run: |
        az webapp deploy --resource-group rg-despesas --name quanto-frontend --src-path ./frontend.zip --type zip

    - name: Reiniciar Web App e Function
      run: |
        az webapp restart --name quanto-frontend --resource-group rg-despesas
        az functionapp restart --name quanto-func --resource-group rg-despesas
