name: Deploy QuantoGastei Azure

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: quanto-frontend
  AZURE_BACKEND_NAME: quanto-backend
  AZURE_FUNCTION_NAME: quanto-func
  AZURE_RG: rg-despesas
  ACR_NAME: acrdespesas

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure CLI - ACR Login
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ env.ACR_NAME }}.azurecr.io/backend:latest

    - name: Criar zip da function
      run: |
        cd function
        zip -r ../function.zip .

    - name: Deploy function zip
      run: |
        az functionapp deployment source config-zip \
          --resource-group ${{ env.AZURE_RG }} \
          --name ${{ env.AZURE_FUNCTION_NAME }} \
          --src function.zip

    - name: Deploy infraestrutura Bicep
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RG }}
        template: infra/main.bicep
        parameters: location=northeurope
        failOnStdErr: false

    - name: Criar zip do frontend
      run: |
        cd frontend
        zip -r ../frontend.zip .

    - name: Deploy frontend zip
      run: |
        az webapp deploy --resource-group ${{ env.AZURE_RG }} --name ${{ env.AZURE_WEBAPP_NAME }} --src-path ./frontend.zip --type zip

    - name: Restart backend and function apps
      run: |
        az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RG }}
        az webapp restart --name ${{ env.AZURE_BACKEND_NAME }} --resource-group ${{ env.AZURE_RG }}
        az webapp restart --name ${{ env.AZURE_FUNCTION_NAME }} --resource-group ${{ env.AZURE_RG }}
