name: Deploy para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        submodules: true

    - name: Verify login
      run: docker info

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: botalmeida/backend-despesas:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: botalmeida/frontend-despesas:latest

    - name: Deploy backend container para Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "backend-webapp-despesas"
        images: docker.io/botalmeida/backend-despesas:latest

    - name: Deploy frontend container para Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "frontend-webapp-despesas"
        images: docker.io/botalmeida/frontend-despesas:latest
