name: Deploy Azure Infra

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker login
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login acrdespesas.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build + Push Backend
      run: |
        docker build -t acrdespesas.azurecr.io/backend:latest ./backend
        docker push acrdespesas.azurecr.io/backend:latest

    - name: Build + Push Function
      run: |
        docker build -t acrdespesas.azurecr.io/function:latest ./function
        docker push acrdespesas.azurecr.io/function:latest

    - name: Deploy Infra
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-despesas
        template: infra/main.bicep
        parameters: location=northeurope
        failOnStdErr: false

    - name: Restart Apps
      run: |
        az webapp restart --name quanto-frontend --resource-group rg-despesas
        az functionapp restart --name quanto-func --resource-group rg-despesas